<?php
$this->mainMenu()->setActiveItemId('nav-faq');
?>
    <div class="media-container">
        <div class="img-bg lazy" data-src="/resources/faq/img/cefalu.jpg"></div>
        <div class="container content">
            <div class="row">
                <div class="col-12">
                    <?php
                    $this->pageBreadcrumbs()->setItems(
                        [
                            $this->translate('Homepage') => $this->url('home', [], ['force_canonical' => true]),
                            $this->translate('FAQ')      => $this->url('faq-front', [], ['force_canonical' => true])
                        ]
                    );
                    echo $this->pageBreadcrumbs()->render();

                    $this->socialSharer()->setUrl($this->url('faq-front', [], ['force_canonical' => true]));
                    $this->socialSharer()->setTitle($this->title);
                    $this->socialSharer()->setTeaser($this->description);
                    $this->socialSharer()->setImage($this->defaultImage);
                    echo $this->socialSharer()->render();
                    ?>
                </div>
            </div>
        </div>
    </div>
    <div class="container content">
        <div class="row">
            <div class="col-12"><h1><?php
                    echo $this->translate('faq-headline'); ?></h1></div>
            <div class="col-12 col-md-6">
                <?php
                echo '<p>' . $this->translate('faq-teaser') . '</p>';
                foreach ($this->categories as $category) {
                    $translatedCategoryName = $this->translate($category['name']['translationKey']);
                    $translatedCategorySlug = $this->translate($category['slug']['translationKey']);
                    $categoryUrl = $this->url('faq-front/category', ['category' => $translatedCategorySlug]);
                    echo '<h2><a href="' . $categoryUrl . '">' . $translatedCategoryName . '</a></h2>';
                    echo '<p>' . $category['description'] . '</p>';

//                    echo '<pre>' . print_r($category, true) . '</pre>';
                    echo '<ul>';
                    foreach ($category['faqs'] as $faq) {
                        $faqUrl = $this->url(
                            'faq-front/category/question',
                            [
                                'category' => $translatedCategorySlug,
                                'slug'     => $faq['slug'],
                            ]
                        );
                        echo '<li><a href="' . $faqUrl . '">' . $faq['question'] . '</a></li>';
                    }
                    echo '</ul>';
                }
                ?>
            </div>
            <div class="col-12 col-md-6 d-flex justify-content-center align-items-center">
                <img src="/resources/faq/img/analyse.svg" class="img-fluid" alt="<?php
                echo $this->translate('faq-headline'); ?>"/>
            </div>
        </div>
    </div>
<?php
if (! empty($this->layout()->cacheId)) {
    $this->inlineScript()->appendFile('/js/basic-' . $this->layout()->cacheId . '.js');
} else {
    $this->inlineScript()
        ->appendFile('/node_modules/jquery/dist/jquery.min.js')
        ->appendFile('/node_modules/jquery-lazy/jquery.lazy.min.js')
        ->appendFile('/resources/application/js/general.js');
}
?>