<?php

/** @var $form Laminas\Form\Form */
$form->prepare();
?>
<div class="container-fluid">
    <div class="row g-3">
        <div class="col-12">
            <h1><?php echo $this->translate('FAQ') . ' - ' .  $this->translate('Create category'); ?></h1>
        </div>
        <div class="col-12">
            <?php
            echo $this->form()->openTag($form);
            echo $this->formRow($form->get('id'));
            if (!empty($this->message) && is_array($this->message)) {
                echo '<div class="alert ' . $this->message["class"] . ' " role="alert">';
                echo $this->translate($this->message['message']);
                echo '</div>';
            }
            if (!empty($form->getMessages()) && is_array($form->getMessages())) {
                echo '<div class="alert alert-danger" role="alert">';
                echo '<pre>' . print_r($form->getMessages(), true) . '</pre>';
                echo '</div>';
            }
            ?>
            <div class="row g-3">
                <div class="col-12 col-md-6">
                    <?php
                    echo $this->formLabel($form->get('name'));
                    echo $this->formSelect($form->get('name'));
                    echo $this->formElementErrors($form->get('name'));
                    ?>
                </div>
                <div class="col-12 col-md-6">
                    <?php
                    echo $this->formLabel($form->get('slug'));
                    echo $this->formSelect($form->get('slug'));
                    echo $this->formElementErrors($form->get('slug'));
                    ?>
                </div>
                <div class="d-grid mt-3">
                    <?php
                    echo $this->formElement($form->get('csrf'));
                    echo $this->formElement($form->get('form-submit'));
                    ?>
                </div>
            </div>
            <?php
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
<?php $this->inlineScript()->appendFile('/resources/admin/js/faq-category-create.js'); ?>
