<?php
$this->mainMenu()->setActiveItemId('faq');
$this->mainMenu()->setActiveItemId('faq-categories');
/** @var TmiFaq\Entity\FaqCategoryEntity $entity */
$entity = $this->entity;
$id = $entity->getId();
/** @var TmiFaq\Form\FaqCategoryForm $form */
$form->prepare();
$form->setAttribute('action', $this->url('faq-back/category/edit', ['id' => $id, 'locale' => $this->locale]));
echo $this->form()->openTag($form);
?>
<div class="container-fluid">
    <div class="row g-3">
        <div class="col-12">
            <h1><?php echo $entity->getTranslationKeyForName(); ?> / <?php
                echo $entity->getTranslationKeyForSlug(); ?></h1>
        </div>
        <div class="col-12">
            <?php
            $this->pageBreadcrumbs()->setItems(
                [
                    $this->translate('Categories')                              => $this->url('faq-back/category'),
                    $this->translate($entity->getName()->getTranslationKey()) => $this->url(
                        'faq-back/category/edit',
                        [
                            'id'     => $id,
                            'locale' => $this->locale
                        ]
                    )
                ]
            );
            echo $this->pageBreadcrumbs()->render();

            echo $this->formRow($form->get('id'));

            if (! empty($this->message) && is_array($this->message)) {
                echo '<div class="alert ' . $this->message["class"] . ' " role="alert">';
                echo $this->translate($this->message['message']);
                echo '</div>';
            }
            if (! empty($form->getMessages()) && is_array($form->getMessages())) {
                echo '<div class="alert alert-danger" role="alert">';
                echo '<pre>' . print_r($form->getMessages(), true) . '</pre>';
                echo '</div>';
            }

            echo $this->partial(
                'tmi-faq/faq-category-back/partial/nav',
                [
                    'id'     => $id,
                    'active' => $this->locale
                ]
            );
            ?>
            <h2><?php echo $this->translate('Description') ?></h2>
        </div>
        <div class="col-12 col-md-6">
            <?php
            echo $this->formLabel($form->get('name'));
            echo $this->formSelect($form->get('name'));
            echo $this->formElementErrors($form->get('name'), ['class' => 'text-danger m-0']); ?>
        </div>
        <div class="col-12 col-md-6">
            <?php
            echo $this->formLabel($form->get('slug'));
            echo $this->formSelect($form->get('slug'));
            echo $this->formElementErrors($form->get('slug'), ['class' => 'text-danger m-0']); ?>
        </div>
        <div class="col-12">
            <div class="form-group">
                <?php
                echo $this->formLabel($form->get('title')); ?>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="titleLength"></span>
                    </div>
                    <?php
                    echo $this->formElement($form->get('title')); ?>
                    <div class="input-group-append">
                        <span class="input-group-text">40-70</span>
                    </div>
                </div>
                <?php echo $this->formElementErrors($form->get('title'), ['class' => 'text-danger m-0']); ?>
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <?php
                echo $this->formLabel($form->get('description')); ?>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="descriptionLength"></span>
                    </div>
                    <?php
                    echo $this->formElement($form->get('description')); ?>
                    <div class="input-group-append">
                        <span class="input-group-text">130-160</span>
                    </div>
                </div>
                <?php echo $this->formElementErrors($form->get('description'), ['class' => 'text-danger m-0']); ?>
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <?php
                echo $this->formLabel($form->get('headline')); ?>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="headlineLength"></span>
                    </div>
                    <?php
                    echo $this->formElement($form->get('headline')); ?>
                    <div class="input-group-append">
                        <span class="input-group-text">40-70</span>
                    </div>
                </div>
                <?php
                echo $this->formElementErrors($form->get('title'), ['class' => 'text-danger m-0']); ?>
            </div>
        </div>
        <div class="col-12">
            <?php
            echo $this->formLabel($form->get('teaser'));
            echo $this->formElement($form->get('teaser'));
            echo $this->formElementErrors($form->get('teaser'), ['class' => 'text-danger m-0']);
            ?>
            <div id="word-count-teaser" class="small"></div>
        </div>
        <div class="col-12">
            <?php
            echo $this->formElement($form->get('csrf'));
            echo $this->formElementErrors($form->get('csrf'), ['class' => 'text-danger m-0']);
            echo $this->formElement($form->get('form-submit'));
            echo $this->formElementErrors($form->get('form-submit'), ['class' => 'text-danger m-0']);
            ?>
        </div>
    </div>
</div>
<?php
echo $this->form()->closeTag();
if (! empty($this->layout()->cacheId)) {
    $this->inlineScript()->appendFile('/js/faq-back-category-edit-' . $this->layout()->cacheId . '.js');
} else {
    $this->inlineScript()
        ->appendFile('/resources/admin/js/ckeditor_extended/build/ckeditor.js')
        ->appendFile('/resources/admin/js/ckeditor_extended/build/translations/de.js')
        ->appendFile('/resources/admin/js/ckeditor_extended/build/translations/it.js')
        ->appendFile('/resources/admin/js/faq-category-edit.js');
}
?>
