<ul class="nav nav-pills nav-fill mb-3">
    <li class="nav-item">
        <a class="nav-link <?php echo $this->active === 'de_DE' ? ' active' : ''; ?>" href="<?php echo $this->url(
            'faq-back/edit',
            [
                'id'     => $this->id,
                'locale' => 'de_DE'
            ]
        ) ?>"><img src="/resources/application/img/germany.png" width="16" height="16" alt="<?php
            echo $this->translate('German'); ?>"/> <?php echo $this->translate('Description'); ?></a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?php echo $this->active === 'en_US' ? ' active' : ''; ?>" href="<?php echo $this->url(
            'faq-back/edit',
            [
                'id'     => $this->id,
                'locale' => 'en_US'
            ]
        ) ?>"><img src="/resources/application/img/usa.png" width="16" height="16" alt="<?php
            echo $this->translate('English'); ?>"/> <?php echo $this->translate('Description'); ?></a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?php echo $this->active === 'it_IT' ? ' active' : ''; ?>" href="<?php echo $this->url(
            'faq-back/edit',
            [
                'id'     => $this->id,
                'locale' => 'it_IT'
            ]
        ) ?>"><img src="/resources/application/img/italy.png" width="16" height="16" alt="<?php
            echo $this->translate('Italian'); ?>"/> <?php echo $this->translate('Description'); ?></a>
    </li>
</ul>