<?php
$this->mainMenu()->setActiveItemId('faq');
$this->mainMenu()->setActiveItemId('faq-questions');
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('faq-back/create'));
echo $this->form()->openTag($form);
?>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <h1><?php echo $this->translate('FAQ') . ' - ' . $this->translate('Create question'); ?></h1>
                <?php
                if (!empty($this->message) && is_array($this->message)) {
                    echo '<div class="alert ' . $this->message["class"] . ' " role="alert">';
                    echo $this->translate($this->message['message']);
                    echo '</div>';
                }
                if (!empty($form->getMessages()) && is_array($form->getMessages())) {
                    echo '<div class="alert alert-danger" role="alert">';
                    echo '<pre>' . print_r($form->getMessages(), true) . '</pre>';
                    echo '</div>';
                }
                ?>
                <div class="row g-3">
                    <div class="col-md-6">
                        <?php
                        echo $this->formLabel($form->get('category'));
                        echo $this->formSelect($form->get('category'));
                        echo $this->formElementErrors($form->get('category'), ['class' => 'text-danger m-0']); ?>
                    </div>
                    <div class="col-md-6">
                        <?php
                        echo $this->formLabel($form->get('categories'));
                        echo $this->formSelect($form->get('categories'));
                        echo $this->formElementErrors($form->get('categories'), ['class' => 'text-danger m-0']); ?>
                    </div>
                    <div class="col-12">
                        <?php
                        echo $this->formLabel($form->get('question')); ?>
                        <div class="input-group">
                            <span id="questionLength" class="input-group-text"></span>
                            <?php
                            echo $this->formElement($form->get('question')); ?>
                            <span class="input-group-text">3-70</span>
                        </div>
                        <?php
                        echo $this->formElementErrors($form->get('question'), ['class' => 'text-danger m-0']); ?>
                    </div>
                </div>
                <div class="d-grid mt-3">
                    <?php
                    echo $this->formElement($form->get('csrf'));
                    echo $this->formElementErrors($form->get('csrf'), ['class' => 'text-danger m-0']);
                    echo $this->formElement($form->get('form-submit'));
                    echo $this->formElementErrors($form->get('form-submit'), ['class' => 'text-danger m-0']);
                    ?>
                </div>
            </div>
        </div>
    </div>
<?php
echo $this->form()->closeTag();
$this->inlineScript()->appendFile('/resources/admin/js/faq-create.js');
?>