<?php
$this->mainMenu()->setActiveItemId('faq');
$this->mainMenu()->setActiveItemId('faq-questions');
/** @var TmiFaq\Entity\FaqEntity $entity */
$entity = $this->entity;
$id = $entity->getId();
/** @var TmiFaq\Form\FaqForm $form */
$form->prepare();
$form->setAttribute('action', $this->url('faq-back/edit', ['id' => $id, 'locale' => $this->locale]));
echo $this->form()->openTag($form);
?>
    <div class="container-fluid">
        <div class="row g-3">
            <div class="col-12">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h1><?php echo $this->question; ?> (<?php echo $id ?>)</h1>
                    </div>
                    <div>
                        <?php
                        if (!empty($this->urlDe)) : ?>
                            <a target="_blank" href="<?php echo $this->urlDe;
                            ?>" class="btn btn-sm btn-primary"><i class="fas fa-external-link-alt"></i> <?php
                                echo $this->translate('German'); ?></a>
                        <?php
                        endif; ?>
                        <?php
                        if (!empty($this->urlEn)) : ?>
                            <a target="_blank" href="<?php echo $this->urlEn
                            ?>" class="btn btn-sm btn-primary"><i class="fas fa-external-link-alt"></i> <?php
                                echo $this->translate('English'); ?>
                            </a>
                        <?php
                        endif; ?>
                        <?php
                        if (!empty($this->urlIt)) : ?>
                            <a target="_blank" href="<?php echo $this->urlIt
                            ?>" class="btn btn-sm btn-primary"><i class="fas fa-external-link-alt"></i> <?php
                                echo $this->translate('Italian'); ?>
                            </a>
                        <?php
                        endif; ?>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <?php
                $this->pageBreadcrumbs()->setItems(
                    [
                        $this->translate('Category') => $this->url('faq-back/category'),
                        $this->translate($entity->getCategory()->getName()->getTranslationKey())
                            => $this->url('faq-back/category/edit',
                            [
                                'id'     => $id,
                                'locale' => $this->locale
                            ]
                        ),
                        $this->translate('Question') => $this->url('faq-back/edit',
                            [
                                'id'     => $id,
                                'locale' => $this->locale
                            ]
                        )
                    ]
                );
                echo $this->pageBreadcrumbs()->render();

                echo $this->formRow($form->get('id'));

                if (!empty($this->message) && is_array($this->message)) {
                    echo '<div class="alert ' . $this->message["class"] . ' " role="alert">';
                    echo $this->translate($this->message['message']);
                    echo '</div>';
                }
                if (!empty($form->getMessages()) && is_array($form->getMessages())) {
                    echo '<div class="alert alert-danger" role="alert">';
                    echo '<pre>' . print_r($form->getMessages(), true) . '</pre>';
                    echo '</div>';
                }

                echo $this->partial(
                    'tmi-faq/faq-back/partial/nav',
                    [
                        'id'     => $id,
                        'active' => $this->locale
                    ]
                );
                ?>
                <h2><?php echo $this->translate('Description') ?></h2>
            </div>
            <div class="col-md-6">
                <?php
                echo $this->formLabel($form->get('category'));
                echo $this->formSelect($form->get('category'));
                echo $this->formElementErrors($form->get('category'), ['class' => 'text-danger m-0']); ?>
            </div>
            <div class="col-md-6">
                <?php
                echo $this->formLabel($form->get('categories'));
                echo $this->formSelect($form->get('categories'));
                echo $this->formElementErrors($form->get('categories'), ['class' => 'text-danger m-0']); ?>
            </div>
            <div class="col-12">
                <?php echo $this->formLabel($form->get('question')); ?>
                <div class="input-group">
                    <span id="questionLength" class="input-group-text"></span>
                    <?php
                    echo $this->formElement($form->get('question')); ?>
                    <span class="input-group-text">3-70</span>
                </div>
                <?php echo $this->formElementErrors($form->get('question'), ['class' => 'text-danger m-0']); ?>
            </div>
            <div class="col-12">
                <?php echo $this->formLabel($form->get('title')); ?>
                <div class="input-group">
                    <span id="titleLength" class="input-group-text"></span>
                    <?php
                    echo $this->formElement($form->get('title')); ?>
                    <span class="input-group-text">3-70</span>
                </div>
                <?php echo $this->formElementErrors($form->get('title'), ['class' => 'text-danger m-0']); ?>
            </div>
            <div class="col-12">
                <?php echo $this->formLabel($form->get('description')); ?>
                <div class="input-group">
                    <span id="descriptionLength" class="input-group-text"></span>
                    <?php
                    echo $this->formElement($form->get('description')); ?>
                    <span class="input-group-text">130-160</span>
                </div>
                <?php echo $this->formElementErrors($form->get('description'), ['class' => 'text-danger m-0']); ?>
            </div>
            <div class="col-12">
                <?php
                echo $this->formLabel($form->get('answer'));
                echo $this->formTextarea($form->get('answer'));
                echo $this->formElementErrors($form->get('answer'), ['class' => 'text-danger m-0']); ?>
            </div>
            <div class="d-grid mt-3">
                <?php
                echo $this->formElement($form->get('csrf'));
                echo $this->formElementErrors($form->get('csrf'), ['class' => 'text-danger m-0']);
                echo $this->formElement($form->get('form-submit'));
                echo $this->formElementErrors($form->get('form-submit'), ['class' => 'text-danger m-0']);
                ?>
            </div>
        </div>
    </div>
<?php
echo $this->form()->closeTag();
if (!empty($this->layout()->cacheId)) {
    $this->inlineScript()->appendFile('/js/faq-edit-' . $this->layout()->cacheId . '.js');
} else {
    $this->inlineScript()
        ->appendFile('/resources/admin/js/ckeditor_extended/build/ckeditor.js')
        ->appendFile('/resources/admin/js/ckeditor_extended/build/translations/de.js')
        ->appendFile('/resources/admin/js/ckeditor_extended/build/translations/it.js')
        ->appendFile('/resources/admin/js/faq-edit.js');
}
?>