<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h1><?php echo $this->translate('FAQ') . ' - ' .  $this->translate('Questions'); ?></h1>
            <a href="<?php echo $this->url('faq-back/create') ?>" class="btn btn-primary mb-3"><?php
                echo $this->translate('Create question') ?></a>

            <div id="content-container" class="form-group mb-3"></div>

            <div class="table-responsive">
                <table id="data-table" class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col"><?php echo $this->translate('Action') ?></th>
                        <th scope="col"><?php echo $this->translate('Action') ?></th>
                        <th scope="col">ID</th>
                        <th scope="col">Position</th>
                        <th scope="col"><?php echo $this->translate('Question') ?></th>
                    </tr>
                    </thead>
                    <tbody id="item_list">
                    <?php
                    foreach ($this->faqs as $faq) :
//                        echo '<pre>' . print_r($faq, true) . '</pre>';

//                        if (!empty($faq['category']['slug']['translationKey'])) {
//
//                            $faqUrlDe = $this->translate('terra-mia-domain', 'default', 'de_DE') . $this->url(
//                                    'faq-front/category/question',
//                                    [
//                                        'category' => $this->translate(
//                                            $faq['category']['slug']['translationKey'],
//                                            'default',
//                                            'de_DE'
//                                        ),
//                                        'slug'     => $faq['slug'],
//                                    ],
//                                    ['locale' => 'de_DE']
//                                );
//                            $copyDe = $faq['question'] . '&#013;&#010;'
//                                . (!empty($supplementDe) ? $supplementDe . '&#013;&#010;' : '') .
//                                $faqUrlDe . '&#013;&#010;&#013;&#010;';
//
//                            $faqUrlEn = $this->translate('terra-mia-domain', 'default', 'en_US') . $this->url(
//                                    'faq-front/category/question',
//                                    [
//                                        'category' => $this->translate(
//                                            $faq['category']['slug']['translationKey'],
//                                            'default',
//                                            'en_US'
//                                        ),
//                                        'slug'     => $faq['slug'],
//                                    ],
//                                    ['locale' => 'en_US']
//                                );
//                            $copyEn = $faq['question'] . '&#013;&#010;'
//                                . (!empty($supplementEn) ? $supplementEn . '&#013;&#010;' : '') .
//                                $faqUrlEn . '&#013;&#010;&#013;&#010;';
//
//                            $faqUrlIt = $this->translate('terra-mia-domain', 'default', 'it_IT') . $this->url(
//                                    'faq-front/category/question',
//                                    [
//                                        'category' => $this->translate(
//                                            $faq['category']['slug']['translationKey'],
//                                            'default',
//                                            'it_IT'
//                                        ),
//                                        'slug'     => $faq['slug'],
//                                    ],
//                                    ['locale' => 'it_IT']
//                                );
//                            $copyIt = $faq['question'] . '&#013;&#010;'
//                                . (!empty($supplementIt) ? $supplementIt . '&#013;&#010;' : '') .
//                                $faqUrlIt . '&#013;&#010;&#013;&#010;';
//                        }
                        ?>
                        <tr id="listItem_<?php echo $faq['id'] ?>">
                            <td>
                                <div class="btn-group btn-group-sm btn-group-toggle">
                                    <a class="btn btn-primary" title="Bearbeiten" href="<?php
                                    echo $this->url("faq-back/edit", ["id" => $faq['id']]);
                                    ?>"><i class="fa fa-edit"></i></a>
                                    <a class="btn btn-outline-primary sortable" title="Sortieren" href="#"><i
                                                class="fas fa-arrows-alt-v"></i></a>
                                </div>
                            </td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group">
                                    <button disabled class="btn btn-outline-primary">
                                        <img alt="<?php echo $this->translate('German') ?>" width="16" height="16"
                                             src="/resources/application/img/germany.png"></button>
                                    <a class="btn btn-outline-primary copy" data-bs-toggle="button"
                                       title="<?php echo $this->translate('copy') ?>"
                                       data-copy="<?php echo $copyDe ?>"><i class="far fa-copy"></i></a>
                                    <a target="_blank" href="<?php echo $faqUrlDe ?>"
                                       class="btn btn-outline-primary"><i class="fas fa-link"></i></a>
                                </div>
                                <div class="btn-group btn-group-sm" role="group">
                                    <button disabled class="btn btn-outline-primary">
                                        <img alt="<?php echo $this->translate('English') ?>" width="16" height="16"
                                             src="/resources/application/img/usa.png"></button>
                                    <a class="btn btn-outline-primary copy" data-bs-toggle="button"
                                       title="<?php echo $this->translate('copy') ?>"
                                       data-copy="<?php echo $copyEn ?>"><i class="far fa-copy"></i></a>
                                    <a target="_blank" href="<?php echo $faqUrlEn ?>"
                                       class="btn btn-outline-primary"><i class="fas fa-link"></i></a>
                                </div>
                                <div class="btn-group btn-group-sm" role="group">
                                    <button disabled class="btn btn-outline-primary">
                                        <img alt="<?php echo $this->translate('Italian') ?>" width="16" height="16"
                                             src="/resources/application/img/italy.png"></button>
                                    <a class="btn btn-outline-primary copy" data-bs-toggle="button"
                                       title="<?php echo $this->translate('copy') ?>"
                                       data-copy="<?php echo $copyIt ?>"><i class="far fa-copy"></i></a>
                                    <a target="_blank" href="<?php echo $faqUrlIt ?>"
                                       class="btn btn-outline-primary"><i class="fas fa-link"></i></a>
                                </div>
                            </td>
                            <td><?php echo $faq['id'] ?></td>
                            <td><?php echo $faq['position'] ?></td>
                            <td><strong><?php echo $faq['question']; ?></strong> (<?php echo $faq['id'] ?>)</td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<?php
$this->headLink()
    ->appendStylesheet('/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css');

if (! empty($this->layout()->cacheId)) {
    $this->inlineScript()->appendFile('/js/faq-back-index-' . $this->layout()->cacheId . '.js');
} else {
    $this->inlineScript()
        ->appendFile('/node_modules/datatables.net/js/jquery.dataTables.min.js')
        ->appendFile('/node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js')
        ->appendFile('/resources/admin/js/faq-index.js');
}
?>
