<?php
$this->mainMenu()->setActiveItemId('sicily');
$this->mainMenu()->setActiveItemId('sicily-edit');
$property = $this->property;
$id = $property->getId();
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
    'sicily/edit/translation',
    [
        'id'     => $id,
        'locale' => $this->locale
    ]
));
?>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <?php
                $this->pageBreadcrumbs()->setItems([
                    $this->translate('Real estate') => $this->url('sicily'),
                    $this->translate('Edit')        => $this->url('sicily/processing'),
                    $property->getName()            => $this->url('sicily/edit', ['id' => $id]),
                    $this->translate('Description') => $this->url('sicily/edit/translation', [
                        'id'     => $id,
                        'locale' => $this->locale
                    ])
                ]);
                echo $this->pageBreadcrumbs()->render();

                echo $this->form()->openTag($form);
                echo $this->formRow($form->get('id'));

                if (!empty($this->message) && is_array($this->message)) {
                    echo '<div class="alert ' . $this->message["class"] . ' " role="alert">';
                    echo $this->translate($this->message['message']);
                    echo '</div>';
                }
                if (!empty($form->getMessages()) && is_array($form->getMessages())) {
                    echo '<div class="alert alert-danger" role="alert">';
                    echo '<pre>' . print_r($form->getMessages(), true) . '</pre>';
                    echo '</div>';
                }

                echo $this->partial(
                    'admin/realestate/partial/nav',
                    [
                        'id'     => $id,
                        'active' => $this->locale
                    ]
                );
                ?>

                <fieldset>
                    <div class="row g-3">
                        <div class="col-12">
                            <?php echo $this->formLabel($form->get('teaser')); ?> (130-150)
                            <div class="input-group">
                                <span id="teaserLength" class="input-group-text"></span>
                                <?php echo $this->formTextarea($form->get('teaser')); ?>
                            </div>
                            <?php echo $this->formElementErrors($form->get('teaser')); ?>
                        </div>
                        <div class="col-12">
                            <?php echo $this->formLabel($form->get('supplement')); ?> (40-100)
                            <div class="input-group">
                                <span id="supplementLength" class="input-group-text"></span>
                                <?php echo $this->formTextarea($form->get('supplement')); ?>
                            </div>
                            <?php echo $this->formElementErrors($form->get('supplement')); ?>
                        </div>
                        <div class="col-12">
                            <div id="descriptionContainer" class="anchor">
                                <?php
                                echo $this->formLabel($form->get('description'));
                                ?>
                                <div id="word-count-description" class="small"></div>
                                <?php
                                echo $this->formTextarea($form->get('description'));
                                echo $this->formElementErrors(
                                    $form->get('description'),
                                    ['class' => 'text-danger small m-0 ms-3']
                                );
                                ?>
                            </div>
                        </div>
                        <div class="col-12">
                            <div id="topographyContainer" class="anchor">
                                <?php
                                echo $this->formLabel($form->get('topography'));
                                ?>
                                <div id="word-count-topography" class="small"></div>
                                <?php
                                echo $this->formTextarea($form->get('topography'));
                                echo $this->formElementErrors(
                                    $form->get('topography'),
                                    ['class' => 'text-danger small m-0 ms-3']
                                );
                                ?>
                            </div>
                        </div>
                        <div class="col-12">
                            <div id="equipmentContainer" class="anchor">
                                <?php
                                echo $this->formLabel($form->get('equipmentText'));
                                ?>
                                <div id="word-count-equipmentText" class="small"></div>
                                <?php
                                echo $this->formTextarea($form->get('equipmentText'));
                                echo $this->formElementErrors(
                                    $form->get('equipmentText'),
                                    ['class' => 'text-danger small m-0 ms-3']
                                );
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="d-grid mt-3">
                        <?php
                        echo $this->formElement($form->get('csrf'));
                        echo $this->formElement($form->get('submit'));
                        ?>
                    </div>
                </fieldset>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
<?php
if (!empty($this->layout()->cacheId)) {
    $this->inlineScript()->appendFile('/js/faq-translation-' . $this->layout()->cacheId . '.js');
} else {
    $this->inlineScript()
        ->appendFile('/resources/admin/js/ckeditor/build/ckeditor.js')
        ->appendFile('/resources/admin/js/ckeditor/build/translations/de.js')
        ->appendFile('/resources/admin/js/ckeditor/build/translations/it.js')
        ->appendFile('/resources/admin/js/faq-translation.js');
}
?>